### ISSUE TITLE
Suggestion: add CITATION.cff

### ISSUE THREAD

**Issue by al42and** [DTolm/VkFFT#172]
GitHub supports [CFF files](https://citation-file-format.github.io/) which facilitate citing software: you can download BibTex file right from the repository page; and in general it seems to become the common place to put the relevant info instead (or in addition to) README.

For VkFFT, this would be a `CITATION.cff` file in the repo root with something like:

```yaml
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: VkFFT
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
authors:
  - given-names: Dmitrii
    family-names: Tolmachev
    orcid: 'https://orcid.org/0000-0002-5494-7983'
repository-code: 'https://github.com/DTolm/VkFFT'
abstract: >-
  VkFFT is an efficient GPU-accelerated multidimensional
  Fast Fourier Transform library for
  Vulkan/CUDA/HIP/OpenCL/Level Zero/Metal projects. VkFFT
  aims to provide the community with an open-source
  alternative to Nvidia's cuFFT library while achieving
  better performance. VkFFT is written in C language and
  supports Vulkan, CUDA, HIP, OpenCL, Level Zero and Metal
  as backends.
keywords:
  - fast fourier transform
  - discrete fourier transform
  - high-performance computing
license: MIT
commit: v1.3.4
version: 1.3.4
date-released: '2024-02-05'

preferred-citation:
  authors:
    - family-names: Tolmachev
      given-names: Dmitrii
  title: >-
    VkFFT-A Performant, Cross-Platform and Open-Source GPU FFT Library
  type: article
  journal: IEEE Access
  volume: 11
  pages: '12039-12058'
  year: 2023
  doi: '10.1109/ACCESS.2023.3242240'
```

This is just an example, you can use [online generator](https://citation-file-format.github.io/cff-initializer-javascript/#/) to modify it or refer to the [format schema](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md).

Note, that the "preferred citation" field is not quite supported by the online generator, but works fine on GitHub: see e.g. https://github.com/ExtremeFLOW/neko ("Cite this repository" in the right sidebar). I also used git tag instead of the commit hash for `commit`: it works well, and it's easier to update when making a new release.
